blank_issues_enabled: true
contact_links:
  - name: Create PR (pull request)
    url: https://github.com/jSagvold28/ProPass/pulls
    about: Create a PR for your implementation to be pushed to production.
