blank_issues_enabled: true
contact_links:
  - name: Bug report
    url: https://github.com/jSagvold28/ProPass/tree/main/.github
    about: Create a bug report.
  - name: Create PR (pull request)
    url: https://github.com/jSagvold28/ProPass/pulls
    about: Create a PR for your implementation to be pushed to production.
